name: weblate_sdk
description: Unofficial WebLate SDK. Designed to work with WebLate web-based continuous localization system.
version: 0.1.0
homepage: https://github.com/cozvtieg9/weblatesdk

environment:
  sdk: '>=2.19.0 <3.0.0'
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  plugin_platform_interface: ^2.1.4
  dio: ^5.1.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  shared_preferences: ^2.1.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  hive_generator: ^2.0.0
  build_runner: ^2.3.3

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  plugin:
    platforms:
      android:
        package: com.weblate.sdk.weblate_sdk
        pluginClass: WeblateSdkPlugin
      ios:
        pluginClass: WeblateSdkPlugin
      linux:
        pluginClass: WeblateSdkPlugin
      macos:
        pluginClass: WeblateSdkPlugin
      windows:
        pluginClass: WeblateSdkPluginCApi
      web:
        pluginClass: WebLateWebPlugin
        fileName: weblate_web_plugin.dart


